### ISSUE TITLE
GPG Public Key is Missing

### ISSUE THREAD

**Issue by samsheff** [ParrotSec/alternate-install#1]
Installation for me is failing on this line:
https://github.com/ParrotSec/alternate-install/blob/96e0e23a4128536309c90866e274a61d541d0492/parrot-install.sh#L35

I checked the URL of the key and it returns a 404. What should this be pulling from now? I'm happy to update it and send a pull request, just need to know where to pull from.

**Comment by samsheff** [comment]
@PalinuroSec Would love to get this working. Any idea what I can do here?

**Comment by PalinuroSec** [comment]
fixed, sorry for the delay

**Comment by Dpentest** [comment]
Hello There
My friend @PalinuroSec it didn't work for me and it keep giving me errors.

![screenshot at 2017-10-20 15-13-12](https://user-images.githubusercontent.com/3456345/31820265-3e28e6c4-b5a9-11e7-837e-faa4a825e8d3.png)

**Comment by PalinuroSec** [comment]
i have re-exported the key on our server and verified to export only the latest version of our archive key.
please re-open the issue if you see that it still does not work

**Comment by NcryptedWifKali** [comment]
what is cmd syntax to install the gpgkey

**Comment by Shaheer-Mirza** [comment]
Please run this code as super user. This will add the Parrot Repository.
```
printf '%s\n' "deb https://deb.parrot.sh/parrot/ parrot main contrib non-free
#deb-src https://deb.parrot.sh/parrot/ parrot main contrib non-free
deb https://deb.parrot.sh/parrot/ parrot-security main contrib non-free
#deb-src https://deb.parrot.sh/parrot/ parrot-security main contrib non-free" |
  sudo tee /etc/apt/sources.list.d/parrot.list
  


curl -fsSL https://deb.parrot.sh/parrot/keyring.gpg |
  sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/parrot-archive-keyring.gpg
```
