### ISSUE TITLE
can't clone the repo

### ISSUE THREAD

**Issue by dytra** [ParrotSec/alternate-install#15]
I got this error when I ran: `git clone https://nest.parrotsec.org/build/alternate-install.git`

```
Cloning into 'alternate-install'...
fatal: unable to access 'https://nest.parrotsec.org/build/alternate-install.git/': server certificate verification failed. CAfile: none CRLfile: none
```

**Comment by iamnotbobby** [comment]
> I got this error when I ran: `git clone https://nest.parrotsec.org/build/alternate-install.git`
> 
> ```
> Cloning into 'alternate-install'...
> fatal: unable to access 'https://nest.parrotsec.org/build/alternate-install.git/': server certificate verification failed. CAfile: none CRLfile: none
> ```

do `curl -O https://raw.githubusercontent.com/ParrotSec/alternate-install/master/parrot-install.sh` or `git clone https://raw.githubusercontent.com/ParrotSec/alternate-install/master/parrot-install.sh`

**Comment by baruffo** [comment]
Yeah unable to clone, even made sure to get the github repository installed on my Debian terminal. I followed these instructions from https://kurdi.dev/blog/parrot-security-on-windows-11-wsl2-with-gui and everything was working until it came to actually installing parrot.

**Comment by Don-Swanson** [comment]
This issue at hand appears to be an expired certificate. If you try to navigate to https://nest.parrotsec.org in your browser you will see they are using a Fake Kubernetes Certificate and since they have HSTS enabled, you won't be able to bypass the fake cert.

**Comment by danterolle** [comment]
> This issue at hand appears to be an expired certificate. If you try to navigate to https://nest.parrotsec.org in your browser you will see they are using a Fake Kubernetes Certificate and since they have HSTS enabled, you won't be able to bypass the fake cert.

Hello everyone! The alternate installer is currently not maintained for quite some time so I would avoid using it. We have decommissioned our GitLab instance and moved to GitLab itself: https://gitlab.com/parrotsec/project

As always GitHub is the backup repository while on GitLab we keep everything up to date, at least the most important projects for ParrotOS.

> Yeah unable to clone, even made sure to get the github repository installed on my Debian terminal. I followed these instructions from https://kurdi.dev/blog/parrot-security-on-windows-11-wsl2-with-gui and everything was working until it came to actually installing parrot.

Before experimenting with the GUI for WSL, I recommend that you use our official version of Parrot specifically built for WSL. For more information, I suggest you to read the documentation: https://parrotsec.org/docs/installation/install-with-wsl

Thank you all.

**Comment by danterolle** [comment]
Hello everyone (again). Due to the simplicity of the project, I wanted to rewrite/revise it mainly to update it to the new version of ParrotOS. I created the (already working) project on GitLab. For any problems please feel free to open other issues or contact me by email. 

https://gitlab.com/parrotsec/project/installer-script

Thank you!

**Comment by iamnotbobby** [comment]
> Hello everyone (again). Due to the simplicity of the project, I wanted to rewrite/revise it mainly to update it to the new version of ParrotOS. I created the (already working) project on GitLab. For any problems please feel free to open other issues or contact me by email.
> 
> https://gitlab.com/parrotsec/project/installer-script
> 
> Thank you!

thanks for the update! thought this repo was completely dead :p
