### ISSUE TITLE
[Cloud] Server not reachable anymore

### ISSUE THREAD

**Issue by Trig0n** [ParrotSec/alternate-install#2]
I got a VPS at Strato(dot)de.
Wantes to install the Cloud Version.
Fresh Debian 7.
Only installed git to clone the project.
Installation went pretty flawless, only thing that caused problems was 'plymouth'. Which did not install, because apparently I had a newer version.

Now the weird stuff:
Above the line where it says 'Finished' or 'Complete' or something like that, it said something like "--force-yes ignored because of -y" and all the installation candidates where listed above (a really huge list of programms and libraries)

Then I did apt-get update, apt-get upgrade and apt-get dist-upgrade.
Apt-get upgrade installed alot of new stuff. (Needed to restart a few services too)
Apt-get dist-upgrade installed a new version of the openssh-server and asked me if i wanted to disable password login for the root user. (I went with no)
Well. That was everything I did. Then I wanted to reboot. Normal "reboot" command did not work because "Could not talk to init handler".
"reboot -f" worked.
After rebooting I can't seem any open port when I scan the server.

Once I get my PC back to work, i am able to provide logs and pictures.

Can anyone tell whats wrong?

**Comment by EclipseSpark** [comment]
you probably have a openvz vps on a shared node that probably doesn't support the kernel modules needed by systemd, so the upgrade to debian 8 failed

you have to reinstall everything, so try to install a fresh debian 8 template (not debian 7) if your provider supports it and retry.

for a better explaination check our cloud page on the new version of our website, it is currently accessible here https://www.parrotsec.org/newsite/cloud.fx and it will be available here https://www.parrotsec.org/cloud.fx within the next week as a replacement of the current website

**Comment by Trig0n** [comment]
Thanks for the response.
Sadly I don't have the option to install Debian 8. (It was at some point, I think.)
So it seems like it won't be possible to install it on my VPS.
I'm going to try it on my Rootserver this evening, that should work out.

For now this issue should be solved. Thanks.
